
version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    container_name: 'db'
    image: postgres:14
    restart: always
    volumes:
      - postgres_data_two:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_ok
    ports:
      - 5432:5432

volumes:
  postgres_data_two:
